# Generated by Django 3.2.5 on 2021-10-10 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras_internas', '0005_auto_20211010_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='compras_internas.oportunidade')),
            ],
        ),
    ]
