# Generated by Django 3.2.5 on 2021-10-10 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras_internas', '0006_registro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pontualcao',
            new_name='Profile',
        ),
    ]
