# Generated by Django 3.2.5 on 2021-10-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_internas', '0010_auto_20211011_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='compras_internas'),
        ),
    ]
